{
  "statusCode": 200,
  "message": "",
  "data": [

    {
      "id": 5,
      "uid": "3c51af91-754a-4302-97c8-53f45456de4f",
      "companyID": 1,
      "workScopeID": 6,
      "calculationType": "SECTION_BASED",
      "inputLabel": "Total Length",
      "inputValue": null,
      "dividerValue": "200",
      "dividerLabel": "Meters per report",
      "unitMeasurement": "METER",
      "photoRequired": false,
      "isActive": true,
      "createdByID": 1,
      "createdAt": "2026-01-02T07:32:37.534Z",
      "updatedAt": "2026-01-02T16:10:50.616Z",
      "deletedAt": null,
      "workScope": {
        "id": 6,
        "uid": "501632f0-e6b5-4054-9d9e-ac349db0d749",
        "name": "Cleaning Drains",
        "code": "R07",
        "description": "Drain cleaning and maintenance works",
        "allowMultipleQuantities": true,
        "companyID": 1,
        "createdAt": "2025-09-16T18:17:04.200Z",
        "updatedAt": "2025-09-16T18:17:04.200Z",
        "deletedAt": null
      },
      "createdBy": {
        "id": 1,
        "uid": "83a0562d-9561-4fbd-8bd1-73ccc87fb9e2",
        "firstName": "Ee Fong",
        "lastName": "Foong",
        "phone": "+60173555706",
        "email": "foongef@gmail.com"
      },
      "quantityTypes": []
    },


    {
      "id": 4,
      "uid": "0027fc75-a3cc-477f-910e-f5ed3ae7e97a",
      "companyID": 1,
      "workScopeID": 5,
      "calculationType": "FIXED_COUNT",
      "inputLabel": "Total Culvert & Bridge",
      "inputValue": null,
      "dividerValue": null,
      "dividerLabel": null,
      "unitMeasurement": "NUMBER",
      "photoRequired": false,
      "isActive": true,
      "createdByID": 1,
      "createdAt": "2026-01-02T07:32:37.491Z",
      "updatedAt": "2026-01-02T16:10:50.469Z",
      "deletedAt": null,
      "workScope": {
        "id": 5,
        "uid": "9711e5f9-cf3a-48a9-99e1-87dc1e82f3ec",
        "name": "Cleaning Culverts & Bridge",
        "code": "R05",
        "description": "Cleaning and maintenance of culverts and bridges",
        "allowMultipleQuantities": true,
        "companyID": 1,
        "createdAt": "2025-09-16T18:17:04.160Z",
        "updatedAt": "2025-09-16T18:17:04.160Z",
        "deletedAt": null
      },
      "createdBy": {
        "id": 1,
        "uid": "83a0562d-9561-4fbd-8bd1-73ccc87fb9e2",
        "firstName": "Ee Fong",
        "lastName": "Foong",
        "phone": "+60173555706",
        "email": "foongef@gmail.com"
      },
      "quantityTypes": []
    },


    {
      "id": 3,
      "uid": "d166b2b1-00fd-45fb-9ad7-8bbe9e351bae",
      "companyID": 1,
      "workScopeID": 4,
      "calculationType": "FIXED_COUNT",
      "inputLabel": "Total Road Furniture",
      "inputValue": null,
      "dividerValue": null,
      "dividerLabel": null,
      "unitMeasurement": "NUMBER",
      "photoRequired": false,
      "isActive": true,
      "createdByID": 1,
      "createdAt": "2026-01-02T07:32:37.449Z",
      "updatedAt": "2026-01-02T16:10:50.432Z",
      "deletedAt": null,
      "workScope": {
        "id": 4,
        "uid": "d0819f60-5be7-4ae9-bccd-00f37f799491",
        "name": "Cleaning Road Furnitures",
        "code": "R04",
        "description": "Cleaning and maintenance of road furniture (signs, barriers, etc.)",
        "allowMultipleQuantities": true,
        "companyID": 1,
        "createdAt": "2025-09-16T18:17:04.119Z",
        "updatedAt": "2025-09-16T18:17:04.119Z",
        "deletedAt": null
      },
      "createdBy": {
        "id": 1,
        "uid": "83a0562d-9561-4fbd-8bd1-73ccc87fb9e2",
        "firstName": "Ee Fong",
        "lastName": "Foong",
        "phone": "+60173555706",
        "email": "foongef@gmail.com"
      },
      "quantityTypes": []
    },
    {
      "id": 2,
      "uid": "34f8d42e-31b5-4b65-aeff-01cb6a360a4a",
      "companyID": 1,
      "workScopeID": 3,
      "calculationType": "SECTION_BASED",
      "inputLabel": "Total Length",
      "inputValue": null,
      "dividerValue": "300",
      "dividerLabel": "Meters per report",
      "unitMeasurement": "METER",
      "photoRequired": false,
      "isActive": true,
      "createdByID": 1,
      "createdAt": "2026-01-02T07:32:37.410Z",
      "updatedAt": "2026-01-02T16:10:50.394Z",
      "deletedAt": null,
      "workScope": {
        "id": 3,
        "uid": "c603b5bc-7325-464d-85d6-5d71331543b2",
        "name": "Grass Cutting",
        "code": "R03",
        "description": "Grass cutting and vegetation management",
        "allowMultipleQuantities": true,
        "companyID": 1,
        "createdAt": "2025-09-16T18:17:04.075Z",
        "updatedAt": "2025-09-16T18:17:04.075Z",
        "deletedAt": null
      },
      "createdBy": {
        "id": 1,
        "uid": "83a0562d-9561-4fbd-8bd1-73ccc87fb9e2",
        "firstName": "Ee Fong",
        "lastName": "Foong",
        "phone": "+60173555706",
        "email": "foongef@gmail.com"
      },
      "quantityTypes": []
    },




    {
      "id": 1,
      "uid": "c72dff69-704d-464b-920a-02883e423e4e",
      "companyID": 1,
      "workScopeID": 2,
      "calculationType": "SECTION_BASED",
      "inputLabel": "Total Length",
      "inputValue": null,
      "dividerValue": "100",
      "dividerLabel": "Meters per report",
      "unitMeasurement": "METER",
      "photoRequired": true,
      "isActive": true,
      "createdByID": 1,
      "createdAt": "2026-01-02T07:32:37.211Z",
      "updatedAt": "2026-01-02T16:10:50.206Z",
      "deletedAt": null,
      "workScope": {
        "id": 2,
        "uid": "81094b15-03b7-4648-bc35-1fd214c90031",
        "name": "Road Shoulder",
        "code": "R02",
        "description": "Road shoulder maintenance and repairs",
        "allowMultipleQuantities": false,
        "companyID": 1,
        "createdAt": "2025-09-16T18:17:04.035Z",
        "updatedAt": "2025-09-16T19:45:09.158Z",
        "deletedAt": null
      },
      "createdBy": {
        "id": 1,
        "uid": "83a0562d-9561-4fbd-8bd1-73ccc87fb9e2",
        "firstName": "Ee Fong",
        "lastName": "Foong",
        "phone": "+60173555706",
        "email": "foongef@gmail.com"
      },


      
      "quantityTypes": [
        {
          "id": 4,
          "programSettingID": 1,
          "quantityTypeID": 7,
          "displayOrder": 0,
          "isRequired": false,
          "createdAt": "2026-01-02T16:10:50.289Z",
          "quantityType": {
            "id": 7,
            "uid": "1f10229c-e100-46d7-a11b-28e8f44ac073",
            "name": "Regrading",
            "code": "REGRADING",
            "description": "Road shoulder regrading with 25m segment breakdown",
            "workScopeID": 2,
            "companyID": 1,
            "displayOrder": 1,
            "isActive": true,
            "hasSegmentBreakdown": true,
            "segmentSize": 25,
            "maxSegmentLength": 1000,
            "createdAt": "2025-09-16T19:55:25.770Z",
            "updatedAt": "2025-09-16T19:55:25.770Z",
            "deletedAt": null,
            "quantityFields": [
              {
                "id": 37,
                "uid": "5a1d6f49-4cbf-419e-821d-9c7d233d21de",
                "quantityTypeID": 7,
                "name": "Direction",
                "code": "direction",
                "fieldType": "DROPDOWN",
                "unit": null,
                "unitMeasurement": null,
                "minValue": null,
                "maxValue": null,
                "minLength": null,
                "maxLength": null,
                "displayOrder": 1,
                "isRequired": true,
                "isForSegment": false,
                "defaultValue": null,
                "placeholder": null,
                "helpText": null,
                "createdAt": "2025-09-16T19:55:25.800Z",
                "updatedAt": "2025-09-16T19:55:25.800Z",
                "dropdownOptions": [
                  {
                    "id": 26,
                    "uid": "c608012f-4ba1-4c7d-b189-0923ac1ae265",
                    "fieldID": 37,
                    "value": "LHS",
                    "displayOrder": 1,
                    "isActive": true,
                    "createdAt": "2025-09-16T19:55:25.827Z",
                    "updatedAt": "2025-09-16T19:55:25.827Z"
                  },
                  {
                    "id": 27,
                    "uid": "58e38d61-d9c1-4653-bee1-e1e244b63d89",
                    "fieldID": 37,
                    "value": "RHS",
                    "displayOrder": 2,
                    "isActive": true,
                    "createdAt": "2025-09-16T19:55:25.842Z",
                    "updatedAt": "2025-09-16T19:55:25.842Z"
                  }
                ]
              },
              {
                "id": 39,
                "uid": "d2a46b5f-7cde-4a88-ad40-d32d78dad00e",
                "quantityTypeID": 7,
                "name": "Segment Length",
                "code": "segment_length",
                "fieldType": "DECIMAL",
                "unit": "m",
                "unitMeasurement": null,
                "minValue": null,
                "maxValue": null,
                "minLength": null,
                "maxLength": null,
                "displayOrder": 1,
                "isRequired": true,
                "isForSegment": true,
                "defaultValue": null,
                "placeholder": null,
                "helpText": null,
                "createdAt": "2025-09-16T19:55:25.901Z",
                "updatedAt": "2025-09-16T19:55:25.901Z",
                "dropdownOptions": []
              },
              {
                "id": 40,
                "uid": "cdbde58d-9d4d-4e6b-be7c-aeefd1ae9575",
                "quantityTypeID": 7,
                "name": "Segment Width",
                "code": "segment_width",
                "fieldType": "DECIMAL",
                "unit": "m",
                "unitMeasurement": null,
                "minValue": null,
                "maxValue": null,
                "minLength": null,
                "maxLength": null,
                "displayOrder": 2,
                "isRequired": false,
                "isForSegment": true,
                "defaultValue": null,
                "placeholder": null,
                "helpText": null,
                "createdAt": "2025-09-16T19:55:25.929Z",
                "updatedAt": "2025-09-16T19:55:25.929Z",
                "dropdownOptions": []
              },
              {
                "id": 38,
                "uid": "90060baf-b835-4063-afb7-1b82bfda4641",
                "quantityTypeID": 7,
                "name": "Total Length",
                "code": "total_length",
                "fieldType": "DECIMAL",
                "unit": "m",
                "unitMeasurement": null,
                "minValue": null,
                "maxValue": null,
                "minLength": null,
                "maxLength": null,
                "displayOrder": 2,
                "isRequired": true,
                "isForSegment": false,
                "defaultValue": null,
                "placeholder": null,
                "helpText": null,
                "createdAt": "2025-09-16T19:55:25.871Z",
                "updatedAt": "2025-09-16T19:55:25.871Z",
                "dropdownOptions": []
              },
              {
                "id": 41,
                "uid": "1e9e0c40-d648-40b3-b4a5-a3996adaa689",
                "quantityTypeID": 7,
                "name": "Segment Depth",
                "code": "segment_depth",
                "fieldType": "DECIMAL",
                "unit": "m",
                "unitMeasurement": null,
                "minValue": null,
                "maxValue": null,
                "minLength": null,
                "maxLength": null,
                "displayOrder": 3,
                "isRequired": false,
                "isForSegment": true,
                "defaultValue": null,
                "placeholder": null,
                "helpText": null,
                "createdAt": "2025-09-16T19:55:25.956Z",
                "updatedAt": "2025-09-16T19:55:25.956Z",
                "dropdownOptions": []
              }
            ]
          }
        },


        {
          "id": 5,
          "programSettingID": 1,
          "quantityTypeID": 8,
          "displayOrder": 1,
          "isRequired": false,
          "createdAt": "2026-01-02T16:10:50.330Z",
          "quantityType": {
            "id": 8,
            "uid": "0843d5b8-9ee5-4ce2-b245-167ae50fe586",
            "name": "Topping up - Laterite",
            "code": "TOPPING_UP_LATERITE",
            "description": "Road shoulder topping up with laterite, 25m segment breakdown",
            "workScopeID": 2,
            "companyID": 1,
            "displayOrder": 2,
            "isActive": true,
            "hasSegmentBreakdown": true,
            "segmentSize": 25,
            "maxSegmentLength": 1000,
            "createdAt": "2025-09-16T19:55:25.983Z",
            "updatedAt": "2025-09-16T19:55:25.983Z",
            "deletedAt": null,
            "quantityFields": [
              {
                "id": 42,
                "uid": "f78e631b-24c6-43ad-a746-5a6982a336b9",
                "quantityTypeID": 8,
                "name": "Direction",
                "code": "direction",
                "fieldType": "DROPDOWN",
                "unit": null,
                "unitMeasurement": null,
                "minValue": null,
                "maxValue": null,
                "minLength": null,
                "maxLength": null,
                "displayOrder": 1,
                "isRequired": true,
                "isForSegment": false,
                "defaultValue": null,
                "placeholder": null,
                "helpText": null,
                "createdAt": "2025-09-16T19:55:26.011Z",
                "updatedAt": "2025-09-16T19:55:26.011Z",
                "dropdownOptions": [
                  {
                    "id": 28,
                    "uid": "b9ddd9ef-385c-4348-aef6-7e74d21ac88f",
                    "fieldID": 42,
                    "value": "LHS",
                    "displayOrder": 1,
                    "isActive": true,
                    "createdAt": "2025-09-16T19:55:26.039Z",
                    "updatedAt": "2025-09-16T19:55:26.039Z"
                  },
                  {
                    "id": 29,
                    "uid": "3111bb5d-958c-4ae9-8ab7-1b04232d9232",
                    "fieldID": 42,
                    "value": "RHS",
                    "displayOrder": 2,
                    "isActive": true,
                    "createdAt": "2025-09-16T19:55:26.063Z",
                    "updatedAt": "2025-09-16T19:55:26.063Z"
                  }
                ]
              },
              {
                "id": 44,
                "uid": "57b64edb-e313-481a-b089-50807bf9cbb7",
                "quantityTypeID": 8,
                "name": "Segment Length",
                "code": "segment_length",
                "fieldType": "DECIMAL",
                "unit": "m",
                "unitMeasurement": null,
                "minValue": null,
                "maxValue": null,
                "minLength": null,
                "maxLength": null,
                "displayOrder": 1,
                "isRequired": true,
                "isForSegment": true,
                "defaultValue": null,
                "placeholder": null,
                "helpText": null,
                "createdAt": "2025-09-16T19:55:26.121Z",
                "updatedAt": "2025-09-16T19:55:26.121Z",
                "dropdownOptions": []
              },
              {
                "id": 43,
                "uid": "10b8febc-3142-4d5e-8ecc-df9bb7716ebd",
                "quantityTypeID": 8,
                "name": "Total Length",
                "code": "total_length",
                "fieldType": "DECIMAL",
                "unit": "m",
                "unitMeasurement": null,
                "minValue": null,
                "maxValue": null,
                "minLength": null,
                "maxLength": null,
                "displayOrder": 2,
                "isRequired": true,
                "isForSegment": false,
                "defaultValue": null,
                "placeholder": null,
                "helpText": null,
                "createdAt": "2025-09-16T19:55:26.093Z",
                "updatedAt": "2025-09-16T19:55:26.093Z",
                "dropdownOptions": []
              },
              {
                "id": 45,
                "uid": "61b8b177-1b98-42df-834d-4413c89fce0e",
                "quantityTypeID": 8,
                "name": "Segment Width",
                "code": "segment_width",
                "fieldType": "DECIMAL",
                "unit": "m",
                "unitMeasurement": null,
                "minValue": null,
                "maxValue": null,
                "minLength": null,
                "maxLength": null,
                "displayOrder": 2,
                "isRequired": false,
                "isForSegment": true,
                "defaultValue": null,
                "placeholder": null,
                "helpText": null,
                "createdAt": "2025-09-16T19:55:26.150Z",
                "updatedAt": "2025-09-16T19:55:26.150Z",
                "dropdownOptions": []
              },
              {
                "id": 46,
                "uid": "e18a1b84-c644-4f65-8fff-702d9ec77c60",
                "quantityTypeID": 8,
                "name": "Segment Depth",
                "code": "segment_depth",
                "fieldType": "DECIMAL",
                "unit": "m",
                "unitMeasurement": null,
                "minValue": null,
                "maxValue": null,
                "minLength": null,
                "maxLength": null,
                "displayOrder": 3,
                "isRequired": false,
                "isForSegment": true,
                "defaultValue": null,
                "placeholder": null,
                "helpText": null,
                "createdAt": "2025-09-16T19:55:26.178Z",
                "updatedAt": "2025-09-16T19:55:26.178Z",
                "dropdownOptions": []
              }
            ]
          }
        },
        {
          "id": 6,
          "programSettingID": 1,
          "quantityTypeID": 9,
          "displayOrder": 2,
          "isRequired": false,
          "createdAt": "2026-01-02T16:10:50.356Z",
          "quantityType": {
            "id": 9,
            "uid": "92533b2f-4096-429e-b4e4-903c091fca03",
            "name": "Topping Up - Crusher Run",
            "code": "TOPPING_UP_CRUSHER_RUN",
            "description": "Road shoulder topping up with crusher run, 25m segment breakdown",
            "workScopeID": 2,
            "companyID": 1,
            "displayOrder": 3,
            "isActive": true,
            "hasSegmentBreakdown": true,
            "segmentSize": 25,
            "maxSegmentLength": 1000,
            "createdAt": "2025-09-16T19:55:26.206Z",
            "updatedAt": "2025-09-16T19:55:26.206Z",
            "deletedAt": null,
            "quantityFields": [
              {
                "id": 47,
                "uid": "7275db55-30e2-4974-8d81-0c8d44b4c35c",
                "quantityTypeID": 9,
                "name": "Direction",
                "code": "direction",
                "fieldType": "DROPDOWN",
                "unit": null,
                "unitMeasurement": null,
                "minValue": null,
                "maxValue": null,
                "minLength": null,
                "maxLength": null,
                "displayOrder": 1,
                "isRequired": true,
                "isForSegment": false,
                "defaultValue": null,
                "placeholder": null,
                "helpText": null,
                "createdAt": "2025-09-16T19:55:26.234Z",
                "updatedAt": "2025-09-16T19:55:26.234Z",
                "dropdownOptions": [
                  {
                    "id": 30,
                    "uid": "25f91101-3a8e-44ae-88b1-96258d55e69d",
                    "fieldID": 47,
                    "value": "LHS",
                    "displayOrder": 1,
                    "isActive": true,
                    "createdAt": "2025-09-16T19:55:26.263Z",
                    "updatedAt": "2025-09-16T19:55:26.263Z"
                  },
                  {
                    "id": 31,
                    "uid": "10323cb5-88e5-4213-ac0a-f0fa6d714e76",
                    "fieldID": 47,
                    "value": "RHS",
                    "displayOrder": 2,
                    "isActive": true,
                    "createdAt": "2025-09-16T19:55:26.277Z",
                    "updatedAt": "2025-09-16T19:55:26.277Z"
                  }
                ]
              },
              {
                "id": 49,
                "uid": "aad302e1-4e32-45cc-a64a-b1b5d37a6a79",
                "quantityTypeID": 9,
                "name": "Segment Length",
                "code": "segment_length",
                "fieldType": "DECIMAL",
                "unit": "m",
                "unitMeasurement": null,
                "minValue": null,
                "maxValue": null,
                "minLength": null,
                "maxLength": null,
                "displayOrder": 1,
                "isRequired": true,
                "isForSegment": true,
                "defaultValue": null,
                "placeholder": null,
                "helpText": null,
                "createdAt": "2025-09-16T19:55:26.333Z",
                "updatedAt": "2025-09-16T19:55:26.333Z",
                "dropdownOptions": []
              },
              {
                "id": 48,
                "uid": "4f5a4b0d-0f67-4366-8f45-074a17d13cbd",
                "quantityTypeID": 9,
                "name": "Total Length",
                "code": "total_length",
                "fieldType": "DECIMAL",
                "unit": "m",
                "unitMeasurement": null,
                "minValue": null,
                "maxValue": null,
                "minLength": null,
                "maxLength": null,
                "displayOrder": 2,
                "isRequired": true,
                "isForSegment": false,
                "defaultValue": null,
                "placeholder": null,
                "helpText": null,
                "createdAt": "2025-09-16T19:55:26.305Z",
                "updatedAt": "2025-09-16T19:55:26.305Z",
                "dropdownOptions": []
              },
              {
                "id": 50,
                "uid": "cd98fa28-51b0-4e40-b932-745ee7faa1b2",
                "quantityTypeID": 9,
                "name": "Segment Width",
                "code": "segment_width",
                "fieldType": "DECIMAL",
                "unit": "m",
                "unitMeasurement": null,
                "minValue": null,
                "maxValue": null,
                "minLength": null,
                "maxLength": null,
                "displayOrder": 2,
                "isRequired": false,
                "isForSegment": true,
                "defaultValue": null,
                "placeholder": null,
                "helpText": null,
                "createdAt": "2025-09-16T19:55:26.364Z",
                "updatedAt": "2025-09-16T19:55:26.364Z",
                "dropdownOptions": []
              },
              {
                "id": 51,
                "uid": "fedb812a-01c0-4ef9-9ff3-1780bf8a72f0",
                "quantityTypeID": 9,
                "name": "Segment Depth",
                "code": "segment_depth",
                "fieldType": "DECIMAL",
                "unit": "m",
                "unitMeasurement": null,
                "minValue": null,
                "maxValue": null,
                "minLength": null,
                "maxLength": null,
                "displayOrder": 3,
                "isRequired": false,
                "isForSegment": true,
                "defaultValue": null,
                "placeholder": null,
                "helpText": null,
                "createdAt": "2025-09-16T19:55:26.393Z",
                "updatedAt": "2025-09-16T19:55:26.393Z",
                "dropdownOptions": []
              }
            ]
          }
        }
      ]
    }
  ],
  "meta": {
    "page": 1,
    "limit": 5,
    "totalCount": 5,
    "totalPages": 1,
    "hasNext": false,
    "hasPrev": false
  }
}