import 'package:flutter/material.dart';
import 'report_model.dart';

// Scope Configurations Data
class ScopeConfigurations {
  static Map<String, ScopeConfig> get all => {
    //R01 - PAVEMENT / PATCHING POTHOLES
    //
    //
    'R01': ScopeConfig(
      id: 'R01',
      name: 'R01 - PAVEMENT / PATCHING POTHOLES',
      commonFields: _getCommonFields(),
      quantityOptions: [
        QuantityOption(
          id: 'potholes',
          name: 'Potholes',
          fields: [
            FieldConfig(
              id: 'method',
              title: 'Method',
              description: 'Choose method',
              icon: Icons.build,
              type: FieldType.dropdown,
              dropdownOptions: ['Method A', 'Method B', 'Method C'],
            ),
            FieldConfig(
              id: 'direction',
              title: 'Direction',
              description: 'Choose direction',
              icon: Icons.navigation,
              type: FieldType.dropdown,
              dropdownOptions: ['North', 'South', 'East', 'West'],
            ),
            FieldConfig(
              id: 'length',
              title: 'Length',
              description: 'Enter length',
              icon: Icons.straighten,
              type: FieldType.numericField,
              hintText: 'Enter length',
              units: 'm',
              numericMin: 0,
              numericMax: 1000,
            ),
            FieldConfig(
              id: 'width',
              title: 'Width',
              description: 'Enter width',
              icon: Icons.width_normal,
              type: FieldType.numericField,
              hintText: 'Enter width',
              units: 'm',
              numericMin: 0,
              numericMax: 100,
            ),
            FieldConfig(
              id: 'thickness',
              title: 'Thickness',
              description: 'Enter thickness',
              icon: Icons.height,
              type: FieldType.numericField,
              hintText: 'Enter thickness',
              units: 'mm',
              numericMin: 0,
              numericMax: 500,
            ),
            FieldConfig(
              id: 'pothole_reference',
              title: 'Pothole Reference',
              description: 'Enter reference',
              icon: Icons.tag,
              type: FieldType.textField,
              hintText: 'Enter reference',
            ),
          ],
        ),
        QuantityOption(
          id: 'crack_sealing',
          name: 'Crack Sealing',
          fields: [
            FieldConfig(
              id: 'direction',
              title: 'Direction',
              description: 'Choose direction',
              icon: Icons.navigation,
              type: FieldType.dropdown,
              dropdownOptions: ['North', 'South', 'East', 'West'],
            ),
            FieldConfig(
              id: 'length',
              title: 'Length',
              description: 'Enter length',
              icon: Icons.straighten,
              type: FieldType.numericField,
              hintText: 'Enter length',
              units: 'm',
              numericMin: 0,
              numericMax: 1000,
            ),
            FieldConfig(
              id: 'width',
              title: 'Width',
              description: 'Enter width',
              icon: Icons.width_normal,
              type: FieldType.numericField,
              hintText: 'Enter width',
              units: 'm',
              numericMin: 0,
              numericMax: 100,
            ),
            FieldConfig(
              id: 'liter',
              title: 'Liter',
              description: 'Enter liter',
              icon: Icons.local_gas_station,
              type: FieldType.numericField,
              hintText: 'Enter liter',
              units: 'L',
              numericMin: 0,
              numericMax: 10000,
            ),
            FieldConfig(
              id: 'material_weight',
              title: 'Material Weight',
              description: 'Enter weight',
              icon: Icons.scale,
              type: FieldType.numericField,
              hintText: 'Enter weight',
              units: 'kg',
              numericMin: 0,
              numericMax: 5000,
            ),
          ],
        ),
        QuantityOption(
          id: 'reconstruction',
          name: 'Reconstruction',
          fields: [
            FieldConfig(
              id: 'method',
              title: 'Method',
              description: 'Choose method',
              icon: Icons.build,
              type: FieldType.dropdown,
              dropdownOptions: ['Method A', 'Method B', 'Method C'],
            ),
            FieldConfig(
              id: 'length',
              title: 'Length',
              description: 'Enter length',
              icon: Icons.straighten,
              type: FieldType.numericField,
              hintText: 'Enter length',
              units: 'm',
              numericMin: 0,
              numericMax: 1000,
            ),
            FieldConfig(
              id: 'width',
              title: 'Width',
              description: 'Enter width',
              icon: Icons.width_normal,
              type: FieldType.numericField,
              hintText: 'Enter width',
              units: 'm',
              numericMin: 0,
              numericMax: 100,
            ),
            FieldConfig(
              id: 'thickness',
              title: 'Thickness',
              description: 'Enter thickness',
              icon: Icons.height,
              type: FieldType.numericField,
              hintText: 'Enter thickness',
              units: 'mm',
              numericMin: 0,
              numericMax: 500,
            ),
          ],
        ),
        QuantityOption(
          id: 'pothole_coldmix',
          name: 'Pothole Coldmix',
          fields: [
            FieldConfig(
              id: 'method',
              title: 'Method',
              description: 'Choose method',
              icon: Icons.build,
              type: FieldType.dropdown,
              dropdownOptions: ['Method A', 'Method B', 'Method C'],
            ),
            FieldConfig(
              id: 'direction',
              title: 'Direction',
              description: 'Choose direction',
              icon: Icons.navigation,
              type: FieldType.dropdown,
              dropdownOptions: ['North', 'South', 'East', 'West'],
            ),
            FieldConfig(
              id: 'length',
              title: 'Length',
              description: 'Enter length',
              icon: Icons.straighten,
              type: FieldType.numericField,
              hintText: 'Enter length',
              units: 'm',
              numericMin: 0,
              numericMax: 1000,
            ),
            FieldConfig(
              id: 'width',
              title: 'Width',
              description: 'Enter width',
              icon: Icons.width_normal,
              type: FieldType.numericField,
              hintText: 'Enter width',
              units: 'm',
              numericMin: 0,
              numericMax: 100,
            ),
            FieldConfig(
              id: 'thickness',
              title: 'Thickness',
              description: 'Enter thickness',
              icon: Icons.height,
              type: FieldType.numericField,
              hintText: 'Enter thickness',
              units: 'mm',
              numericMin: 0,
              numericMax: 500,
            ),
            FieldConfig(
              id: 'pothole_reference',
              title: 'Pothole Reference',
              description: 'Enter reference',
              icon: Icons.tag,
              type: FieldType.textField,
              hintText: 'Enter reference',
            ),
            FieldConfig(
              id: 'coldmix_quantity',
              title: 'Coldmix Quantity',
              description: 'Enter quantity',
              icon: Icons.format_list_numbered,
              type: FieldType.numericField,
              hintText: 'Enter quantity',
              units: 'kg',
              numericMin: 0,
              numericMax: 5000,
            ),
          ],
        ),
        QuantityOption(
          id: 'asphalt_heater',
          name: 'Asphalt Heater',
          fields: [
            FieldConfig(
              id: 'pothole_reference',
              title: 'Pothole Reference',
              description: 'Enter reference',
              icon: Icons.tag,
              type: FieldType.textField,
              hintText: 'Enter reference',
            ),
            FieldConfig(
              id: 'direction',
              title: 'Direction',
              description: 'Choose direction',
              icon: Icons.navigation,
              type: FieldType.dropdown,
              dropdownOptions: ['North', 'South', 'East', 'West'],
            ),
            FieldConfig(
              id: 'thickness',
              title: 'Thickness',
              description: 'Enter thickness',
              icon: Icons.height,
              type: FieldType.numericField,
              hintText: 'Enter thickness',
              units: 'mm',
              numericMin: 0,
              numericMax: 500,
            ),
            FieldConfig(
              id: 'panels_used',
              title: 'Number of Panels Used',
              description: 'Enter number',
              icon: Icons.grid_view,
              type: FieldType.numericField,
              hintText: 'Enter number',
              numericMin: 0,
              numericMax: 100,
            ),
            FieldConfig(
              id: 'coldmix_quantity',
              title: 'Coldmix Quantity',
              description: 'Enter quantity',
              icon: Icons.format_list_numbered,
              type: FieldType.numericField,
              hintText: 'Enter quantity',
              units: 'kg',
              numericMin: 0,
              numericMax: 5000,
            ),
            FieldConfig(
              id: 'gas_lpg_quantity',
              title: 'Gas LPG Quantity',
              description: 'Enter quantity',
              icon: Icons.local_gas_station,
              type: FieldType.numericField,
              hintText: 'Enter quantity',
              units: 'kg',
              numericMin: 0,
              numericMax: 100,
            ),
            FieldConfig(
              id: 'rejuvenating_agent_quantity',
              title: 'Rejuvenating Agent Quantity',
              description: 'Enter quantity',
              icon: Icons.opacity,
              type: FieldType.numericField,
              hintText: 'Enter quantity',
              units: 'L',
              numericMin: 0,
              numericMax: 1000,
            ),
          ],
        ),
        QuantityOption(
          id: 'heavy_patching',
          name: 'Heavy Patching',
          fields: [
            FieldConfig(
              id: 'method',
              title: 'Method',
              description: 'Choose method',
              icon: Icons.build,
              type: FieldType.dropdown,
              dropdownOptions: ['Method A', 'Method B', 'Method C'],
            ),
            FieldConfig(
              id: 'direction',
              title: 'Direction',
              description: 'Choose direction',
              icon: Icons.navigation,
              type: FieldType.dropdown,
              dropdownOptions: ['North', 'South', 'East', 'West'],
            ),
            FieldConfig(
              id: 'length',
              title: 'Length',
              description: 'Enter length',
              icon: Icons.straighten,
              type: FieldType.numericField,
              hintText: 'Enter length',
              units: 'm',
              numericMin: 0,
              numericMax: 1000,
            ),
            FieldConfig(
              id: 'width',
              title: 'Width',
              description: 'Enter width',
              icon: Icons.width_normal,
              type: FieldType.numericField,
              hintText: 'Enter width',
              units: 'm',
              numericMin: 0,
              numericMax: 100,
            ),
            FieldConfig(
              id: 'thickness',
              title: 'Thickness',
              description: 'Enter thickness',
              icon: Icons.height,
              type: FieldType.numericField,
              hintText: 'Enter thickness',
              units: 'mm',
              numericMin: 0,
              numericMax: 500,
            ),
            FieldConfig(
              id: 'pothole_reference',
              title: 'Pothole Reference',
              description: 'Enter reference',
              icon: Icons.tag,
              type: FieldType.textField,
              hintText: 'Enter reference',
            ),
          ],
        ),
      ],
    ),

    //R02 - ROAD SHOULDER
    //
    //
    'R02': ScopeConfig(
      id: 'R02',
      name: 'R02 - ROAD SHOULDER',
      commonFields: _getCommonFields(),
      quantityOptions: [
        QuantityOption(
          id: 'road_shoulder',
          name: 'Road Shoulder Work',
          fields: [
            FieldConfig(
              id: 'direction',
              title: 'Direction',
              description: 'Choose direction',
              icon: Icons.navigation,
              type: FieldType.dropdown,
              dropdownOptions: ['North', 'South', 'East', 'West'],
            ),
            FieldConfig(
              id: 'method',
              title: 'Method',
              description: 'Choose method',
              icon: Icons.build,
              type: FieldType.dropdown,
              dropdownOptions: ['Method A', 'Method B', 'Method C'],
            ),
            FieldConfig(
              id: 'length',
              title: 'Length',
              description: 'Enter length',
              icon: Icons.straighten,
              type: FieldType.numericField,
              hintText: 'Enter length',
              units: 'm',
              numericMin: 0,
              numericMax: 1000,
            ),
          ],
        ),
      ],
    ),
    'R03': ScopeConfig(
      id: 'R03',
      name: 'R03 - GRASS CUTTING',
      commonFields: _getCommonFields(),
      quantityOptions: [
        QuantityOption(
          id: 'grass_cutting',
          name: 'Grass Cutting',
          fields: [
            FieldConfig(
              id: 'direction',
              title: 'Direction',
              description: 'Choose direction',
              icon: Icons.navigation,
              type: FieldType.dropdown,
              dropdownOptions: ['North', 'South', 'East', 'West'],
            ),
            FieldConfig(
              id: 'length',
              title: 'Length',
              description: 'Enter length',
              icon: Icons.straighten,
              type: FieldType.numericField,
              hintText: 'Enter length',
              units: 'm',
              numericMin: 0,
              numericMax: 1000,
            ),
            FieldConfig(
              id: 'width',
              title: 'Width',
              description: 'Enter width',
              icon: Icons.width_normal,
              type: FieldType.numericField,
              hintText: 'Enter width',
              units: 'm',
              numericMin: 0,
              numericMax: 100,
            ),
            FieldConfig(
              id: 'thickness',
              title: 'Thickness',
              description: 'Enter thickness',
              icon: Icons.height,
              type: FieldType.numericField,
              hintText: 'Enter thickness',
              units: 'mm',
              numericMin: 0,
              numericMax: 500,
            ),
          ],
        ),
        QuantityOption(
          id: 'clearing_vegetation',
          name: 'Clearing Vegetation',
          fields: [
            FieldConfig(
              id: 'direction',
              title: 'Direction',
              description: 'Choose direction',
              icon: Icons.navigation,
              type: FieldType.dropdown,
              dropdownOptions: ['North', 'South', 'East', 'West'],
            ),
            FieldConfig(
              id: 'edge_pavement',
              title: 'Edge Pavement',
              description: 'Enter edge pavement',
              icon: Icons.linear_scale,
              type: FieldType.numericField,
              hintText: 'Enter measurement',
              units: 'm',
              numericMin: 0,
              numericMax: 1000,
            ),
            FieldConfig(
              id: 'kerb_length',
              title: 'Kerb Length',
              description: 'Enter kerb length',
              icon: Icons.straighten,
              type: FieldType.numericField,
              hintText: 'Enter length',
              units: 'm',
              numericMin: 0,
              numericMax: 1000,
            ),
          ],
        ),
      ],
    ),
  };

  static List<FieldConfig> _getCommonFields() {
    return [
      FieldConfig(
        id: 'worker_pictures',
        title: 'Worker (Pictures)',
        description: 'Add worker pictures',
        icon: Icons.person,
        type: FieldType.multipleImages,
        isRequired: true,
      ),
      FieldConfig(
        id: 'equipment',
        title: 'Equipment',
        description: 'Enter equipment details',
        icon: Icons.construction,
        type: FieldType.textField,
        hintText: 'Enter equipment used',
        isRequired: true,
      ),
      FieldConfig(
        id: 'condition_snapshot',
        title: 'Condition Snapshot (Before, Current, After)',
        description: 'Add condition photos',
        icon: Icons.camera_alt,
        type: FieldType.multipleImages,
        isRequired: true,
      ),
      FieldConfig(
        id: 'notes',
        title: 'Notes',
        description: 'Additional notes',
        icon: Icons.note,
        type: FieldType.notes,
        hintText: 'Enter additional notes',
      ),
    ];
  }
}
